package ServiceLayer;

import java.util.Set;
import javax.ws.rs.core.Application;
import javax.ws.rs.*;

@ApplicationPath("resources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(ServiceLayer.Service.class);
        return resources;
    }
}
